package net.globulus.mmap;

import java.io.Serializable;

/**
 * An annotation processor should use an input to generate its source files. Have your processor's
 * input extend this interface, passing the class that's implementing the interface as the param.
 * @param <T> The class that's implementing the interface. E.g:
 *           class MyInput implements MergeInput&lt;MyInput&gt; {
 */
public interface MergeInput<T extends MergeInput<T>> extends Serializable {

    /**
     * Defines how does merge conflict resolution work for your input class when it's merged with
     * the input from higher up in the module hierarchy.
     * @param other The input generated by the processor run for a module higher up.
     * @return The merged input.
     */
    T mergedUp(T other);
}
